server:
  port: 8886

spring:
  application:
    name: leucam-telegram-bot-service
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:file:./data/leucam_telegram_bot
    driver-class-name: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect
    username: root
    password:
  rabbitmq:
    addresses: amqp://***
    cloud:
      stream:
        bindings:
          userRegistrationChannel:
            destination: leucam-user-registration
          userOrderChannel:
            destination: leucam-order-registration
          orderUpdateChannel:
            destination: leucam-order-update
          orderCancellationChannel:
            destination: leucam-order-cancellation
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000

leucam:
  repository:
    path: c:/lcpm/products/
    extension: .pdf

  telegram:
    bot:
      username: YOUR_USERNAME
      token: YOUR_TOKEN

  template:
    paymentInternalCreditURL: http://192.168.1.12:8881/gassman-payment-service/public/internal-credit/make/payment/%d

  api:
    username:
    password: